# Version
targetJavaVersion=17
group=su.plo.voice
version=2.2.0

# Gradle args
org.gradle.jvmargs=-Xmx4G -Dkotlin.daemon.jvm.options=-Xmx1G --enable-native-access=ALL-UNNAMED
org.gradle.workers.max=4
org.gradle.parallel=true
org.gradle.caching=true
kotlin.stdlib.default.dependency=false

# default 3
org.gradle.internal.repository.max.tentatives=5
