essential.defaults.loom.minecraft=com.mojang:minecraft:26.3
essential.defaults.loom.fabric-loader=net.fabricmc:fabric-loader:0.19.5
essential.defaults.loom.mappings=

mod.minecraft_versions=>=26.3 <26.4

deps.slib=26.1

deps.fabric_api=0.160.5+26.3
deps.fabric_permissions_api=0.7.0
deps.cloth_config=26.3.158
deps.modmenu=21.0.0-beta.1
