name: Setup build

runs:
  using: composite
  steps:
  - name: Set up JDK
    uses: actions/setup-java@v5.7.0
    with:
      distribution: temurin
      java-version: |
        8
        16
        17
        21
        25

  - name: Setup Gradle
    uses: gradle/actions/setup-gradle@v6.3.0
    with:
      add-job-summary: on-failure
