package su.plo.voice.api.proxy.socket;

import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;
import su.plo.voice.api.proxy.player.VoiceProxyPlayer;
import su.plo.voice.api.proxy.server.RemoteServer;
import su.plo.voice.api.server.socket.UdpConnection;

import java.util.Optional;
import java.util.UUID;

/**
 * Identified UDP proxy connection between the proxy and a player.
 */
public interface UdpProxyConnection extends UdpConnection {

    /**
     * Gets the player associated with this proxy connection.
     *
     * @return The {@link VoiceProxyPlayer} associated with this connection.
     */
    @NotNull VoiceProxyPlayer getPlayer();

    /**
     * Gets the remote secret associated with this proxy connection.
     *
     * <p>
     *     Remote secret is a secret, received from the remote backend and used for communication between proxy and backend.
     * </p>
     *
     * @return The remote secret as a {@link UUID}.
     */
    @NotNull UUID getRemoteSecret();

    /**
     * Gets the proxy secret associated with this proxy connection.
     *
     * <p>
     *     Proxy secret is a secret, generated by the proxy and used for communication between proxy and player.
     * </p>
     *
     * @return The proxy secret as a {@link UUID}.
     */
    @NotNull default UUID getProxySecret() {
        return getSecret();
    }

    /**
     * Sets the remote secret associated with this proxy connection.
     *
     * @param remoteSecret The remote secret as a {@link UUID}.
     */
    void setRemoteSecret(@NotNull UUID remoteSecret);

    /**
     * Gets the remote server associated with this proxy connection.
     *
     * @return The {@link RemoteServer} representing the remote backend server.
     */
    Optional<RemoteServer> getRemoteServer();

    /**
     * Sets the remote server associated with this proxy connection.
     *
     * @param remoteServer The {@link RemoteServer} representing the remote backend server.
     */
    void setRemoteServer(@NotNull RemoteServer remoteServer);
}
