name: Publish PR Snapshot

on:
  pull_request:
    types:
      - synchronize
      - opened
      - ready_for_review
      - reopened

concurrency:
  group: pr-${{ github.event.pull_request.number }}
  cancel-in-progress: false

jobs:
  build:
    uses: ./.github/workflows/build.yml
    with:
      snapshot: true

  build-rest:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v7.0.1
    - uses: ./.github/actions/setup-build

    - name: Build with Gradle (everything except client)
      run: ./gradlew build --stacktrace -Pproject.client.disable=true -Psnapshot=true
