name: Publish PR Snapshot

on:
  pull_request:
    types:
      - synchronize
      - opened
      - ready_for_review
      - reopened

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    steps:
    - uses: actions/checkout@v6
    - name: Set up JDK
      uses: actions/setup-java@v5.7.0
      with:
        distribution: temurin
        java-version: |
          8
          16
          17
          21

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v6.3.0
      with:
        cache-read-only: false

    - name: Build with Gradle
      run: ./gradlew build --stacktrace -Psnapshot=true

    - name: Upload build artifacts
      uses: plasmoapp/actions/.github/actions/upload-artifacts@main
      with:
        files_glob: build/libs/*.jar
        archive: false
        retention_days: 7
        summary: false
